### ISSUE TITLE
Fix label for 'Visual Settings' group

### ISSUE THREAD

**Issue by ymdahi** [otacke/h5p-x-ray#1]
The label for the 'Visual Settings' group currently read "20%" instead of "Visual Settings". Screenshot below.

![Screenshot 2022-02-17 215657](https://user-images.githubusercontent.com/3291625/154611043-6a53bb51-43a7-4ddf-87fb-cc8f75b1a9de.jpg)

I've made attempts to troubleshoot/fix, but honestly can not find any reason why this is not reading "Visual Settings" as defined below:

https://github.com/otacke/h5p-x-ray/blob/b8a51e193fb98c54f3783cdfe58285bcab814222/semantics.json#L25

**Comment by otacke** [comment]
See https://github.com/h5p/h5p-editor-php-library/issues/134
