### ISSUE TITLE
Uploading H5P.XRay.h5p has message: "upload has been renamed to H5P.XRay_.h5p."

### ISSUE THREAD

**Issue by ymdahi** [otacke/h5p-x-ray#2]
![Screenshot 2022-02-17 222008](https://user-images.githubusercontent.com/3291625/154611471-0d6c6a4d-2605-40ef-9b7b-9ad12e6192d6.jpg)

This is most likely a Drupal thing, but I am not sure why it would think to place a '_' after XRay. There doesn't seem to be any indication of an empty space or special character that would cause this renaming.

This does not interfere with the upload process, and the content type is functional regardless of this message.

**Comment by otacke** [comment]
See  https://www.drupal.org/forum/support/post-installation/2013-02-04/for-security-reasons-your-upload-has-been-renamed-to
